#!/usr/bin/bash

CONFFILE="/etc/ipfixprobe/$1.conf"

if [ -e "$CONFFILE" ]; then
   source "$CONFFILE"
   input=""
   if `declare -p INPUT > /dev/null 2>/dev/null`; then
      # list of input plugins
      for ifc in "${!INPUT[@]}"; do
         input="$input -i ${INPUT[ifc]}"
      done
   fi
   CACHE_SIZE_PARAM=""
   if [ ! -z ${CACHE_SIZE+x} ]; then
      CACHE_SIZE_PARAM="size=${CACHE_SIZE}"
   fi
   CACHE_ACTIVET_PARAM=""
   if [ ! -z ${ACTIVE_TIMEOUT+x} ]; then
      CACHE_ACTIVET_PARAM=";active=${ACTIVE_TIMEOUT}"
   fi
   CACHE_INACTIVET_PARAM=""
   if [ ! -z ${INACTIVE_TIMEOUT+x} ]; then
      CACHE_INACTIVET_PARAM=";inactive=${INACTIVE_TIMEOUT}"
   fi
   storage="-s cache;${CACHE_SIZE_PARAM}${CACHE_ACTIVET_PARAM}${CACHE_INACTIVET_PARAM}"
   process=""
   if `declare -p PROCESS > /dev/null 2>/dev/null`; then
      # list of input plugins
      for ifc in "${!PROCESS[@]}"; do
         process="$process -p ${PROCESS[ifc]}"
      done
   fi
   UDP_PARAM=""
   if [[ $UDP == "yes" ]]; then
        UDP_PARAM="udp";
   fi
   output="-o ipfix;host=${HOST:-127.0.0.1};port=${PORT:-4739};id=${LINK:-0};dir=${DIR:-0};${UDP_PARAM}"

   if [ -n "$DPDKARGS" ]; then
      exec /usr/bin/ipfixprobe $DPDKARGS -- $input $storage $process $output
   else
      exec /usr/bin/ipfixprobe $input $storage $process $output
   fi
else
   echo "Configuration file '$CONFFILE' does not exist, exitting." >&2
   exit 1
fi
