#!/usr/bin/bash

CONFFILE="/etc/ipfixprobe/$1.conf"

if [ -e "$CONFFILE" ]; then
   source "$CONFFILE"
   if [ "$UDP" = yes ]; then
      udpparam=-u
   else
      udpparam=""
   fi
   ifcargs=""
   if `declare -p IFCLIST > /dev/null 2>/dev/null`; then
      # list of interfaces/DMA channels
      for ifc in "${!IFCLIST[@]}"; do
         ifcargs="$ifcargs -I ${IFCLIST[ifc]}"
      done
   else
      # use plain old one NIC interface
      if [ -z "$NIC" ]; then
         echo "Configuration file '$CONFFILE' does not exist, exitting." >&2
         exit 1
      fi
      ifcargs="-I $NIC"
   fi
   exec /usr/bin/ipfixprobe $ifcargs -p "$PLUGINS" -L "$LINK" -D "$DIR" -x "$COLLECTOR" $udpparam
else
   echo "Configuration file '$CONFFILE' does not exist, exitting." >&2
   exit 1
fi

