# ----
# Site

title: ipfixprobe - High-performance IPFIX probe
url: "https://cesnet.github.io/ipfixprobe/"
baseurl: https://cesnet.github.io/ipfixprobe/ # comment out for local development
#baseurl: # uncomment for local development
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.svg
description: "ipfixprobe is a tool for creating network flows and exporting them to a remote collector using the IPFIX protocol. It is an essential tool for maintinaing network security."
author:
  name: "Karel Hynek (CESNET z.s.p.o.)"
  email: "hynekkar@cesnet.cz"
  twitter: # twitter username without the @ symbol
social:
  name: "Hydra Template"
  links:
    - https://github.com/CloudCannon/hydra-jekyll-template

# -----
# Build

timezone: Etc/UTC

collections:
  staff_members:
    _hide_content: true
  get_options:
    _hide_content: true
  how:
    _hide_content: true
    output: true
  export:
    _hide_content: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1500
          height: 2500
  - scope:
      path: ""
      type: "staff_members"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: "index.html"
    values:
      layout: "default"
  - scope:
      path: "get_options"
    values:
      layout: "post"
  - scope:
      path: "contact.html"
    values:
      full_width: true

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

_select_data:
  social_icons:
    - Facebook
    - Instagram
    - LinkedIn
    - Pinterest
    - Tumblr
    - Twitter
    - YouTube
    - RSS

