name: check

on: [workflow_call]
    
jobs:
  clang-checks:
    runs-on: ubuntu-latest
    container: oraclelinux:9
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        dnf copr enable @CESNET/NEMEA
        dnf install -y make gcc-c++ git autoconf libtool epel-release
        dnf config-manager --enable ol9_codeready_builder*
        dnf install -y gcc-toolset-13-libatomic-devel doxygen openssl-devel
    - name: autoreconf
      run: autoreconf -i
    - name: configure
      run: ./configure
    - name: make
      run: make
#    - name: make format-check
#      run: make format
#    - name: make tidy-check
#      run: make tidy

  editor-config:
    runs-on: ubuntu-latest
    container: mstruebing/editorconfig-checker
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Check editorconfig
      run: ec --exclude .git

  include-orders:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Run include-order-checker
      run: "! grep -r -A 10 '#include <' include/ input/ output/ process/ storage/ | grep -B 10 '#include \"'"

#  cppcheck:
#    uses: ./.github/workflows/cppcheck.yml


# clang clang-tools-extra  fuse3-devel 